### PR TITLE
Do not treat failure to collect metrics as fatal

### PR DESCRIPTION
**Pull request by pracucci**
Reverts PR #83 (see discussion in the issue for more information).

### CODE REVIEW

**Comment by SuperQ** [comment]
Thanks. @cpick, do you have a specific error that we could handle for credentials not being valid anymore?

**Comment by psalaberria002** [comment]
We are seeing constant restarts due to timeouts against stackdriver. Would be nice if we can get the previous behaviour back.

**Comment by SuperQ** [comment]
Yes, I agree, let's merge this and work on what to do about the credential case separately.

**Comment by cpick** [comment]
Following up on handling the authentication issues more specifically in #101.

**Comment by psalaberria002** [comment]
A release with this fix would be great :)

**Comment by psalaberria002** [comment]
@SuperQ ^^

**Pull request merged**
