### PR TITLE
Refactor flags

### PR DESCRIPTION
**Pull request by SuperQ**
Move flags needed by the collector into the collectors package. This
simplifies exporter setup.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
cc @igorwwwwwwwwwwwwwwwwwwww

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
It might be a bit surprising to have flags implicitly imported (and mutate global state on import). But since there are no external consumers, this looks ok to me. :)

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
It might be a bit surprising to have flags implicitly imported (and mutate global state on import). But since there are no external consumers, this looks ok to me. :)

**Comment by SuperQ** [comment]
Yes, this is a pattern we use in other Prometheus exporters. There are possibly better ways to do this, like configure a struct, but I feel like this is a simpler way for now.

**Pull request merged**
