### PR TITLE
Add stackdriver timestamp to metrics

### PR DESCRIPTION
**Pull request by achilles42**
Co-authored-by: Vishal Raj <lahsivjar@gmail.com>

Add stackdriver timestamp in metrics. 
Fixes [58](https://github.com/frodenas/stackdriver_exporter/issues/58)

### CODE REVIEW

**Comment by achilles42** [comment]
Hey @frodenas, Please let me know if you have any feedback on the PR.

**Comment by SuperQ** [comment]
This needs a rebase to pick up the changes to vendoring.

**Comment by lahsivjar** [comment]
@SuperQ Created PR with the required changes: #84 

Please help to check

**Comment by SuperQ** [comment]
Superseded by https://github.com/prometheus-community/stackdriver_exporter/pull/84

**Pull request closed without merging**
